-- ============================================================================
-- DESTINOS DEL MUNDO + CODIGO IATA (sin Africa ni Asia poco conocida)
-- Idempotente: actualiza el IATA/pais si el destino ya existe (por nombre).
-- Correr en el SQL editor de Supabase.
-- ============================================================================
insert into public.destinos (nombre, codigo_iata, pais, activo) values
  ('BOGOTA', 'BOG', 'COLOMBIA', true),
  ('MEDELLIN', 'MDE', 'COLOMBIA', true),
  ('CARTAGENA', 'CTG', 'COLOMBIA', true),
  ('SANTA MARTA', 'SMR', 'COLOMBIA', true),
  ('CALI', 'CLO', 'COLOMBIA', true),
  ('BARRANQUILLA', 'BAQ', 'COLOMBIA', true),
  ('SAN ANDRES', 'ADZ', 'COLOMBIA', true),
  ('PEREIRA', 'PEI', 'COLOMBIA', true),
  ('ARMENIA', 'AXM', 'COLOMBIA', true),
  ('BUCARAMANGA', 'BGA', 'COLOMBIA', true),
  ('CUCUTA', 'CUC', 'COLOMBIA', true),
  ('MONTERIA', 'MTR', 'COLOMBIA', true),
  ('RIOHACHA', 'RCH', 'COLOMBIA', true),
  ('VALLEDUPAR', 'VUP', 'COLOMBIA', true),
  ('LETICIA', 'LET', 'COLOMBIA', true),
  ('PASTO', 'PSO', 'COLOMBIA', true),
  ('MANIZALES', 'MZL', 'COLOMBIA', true),
  ('IBAGUE', 'IBE', 'COLOMBIA', true),
  ('NEIVA', 'NVA', 'COLOMBIA', true),
  ('VILLAVICENCIO', 'VVC', 'COLOMBIA', true),
  ('QUIBDO', 'UIB', 'COLOMBIA', true),
  ('POPAYAN', 'PPN', 'COLOMBIA', true),
  ('TUMACO', 'TCO', 'COLOMBIA', true),
  ('APARTADO', 'APO', 'COLOMBIA', true),
  ('YOPAL', 'EYP', 'COLOMBIA', true),
  ('MIAMI', 'MIA', 'NORTEAMERICA', true),
  ('ORLANDO', 'MCO', 'NORTEAMERICA', true),
  ('NUEVA YORK', 'JFK', 'NORTEAMERICA', true),
  ('LOS ANGELES', 'LAX', 'NORTEAMERICA', true),
  ('LAS VEGAS', 'LAS', 'NORTEAMERICA', true),
  ('FORT LAUDERDALE', 'FLL', 'NORTEAMERICA', true),
  ('HOUSTON', 'IAH', 'NORTEAMERICA', true),
  ('DALLAS', 'DFW', 'NORTEAMERICA', true),
  ('CHICAGO', 'ORD', 'NORTEAMERICA', true),
  ('WASHINGTON', 'IAD', 'NORTEAMERICA', true),
  ('BOSTON', 'BOS', 'NORTEAMERICA', true),
  ('SAN FRANCISCO', 'SFO', 'NORTEAMERICA', true),
  ('ATLANTA', 'ATL', 'NORTEAMERICA', true),
  ('SEATTLE', 'SEA', 'NORTEAMERICA', true),
  ('DENVER', 'DEN', 'NORTEAMERICA', true),
  ('TORONTO', 'YYZ', 'NORTEAMERICA', true),
  ('MONTREAL', 'YUL', 'NORTEAMERICA', true),
  ('VANCOUVER', 'YVR', 'NORTEAMERICA', true),
  ('CIUDAD DE MEXICO', 'MEX', 'NORTEAMERICA', true),
  ('CANCUN', 'CUN', 'NORTEAMERICA', true),
  ('GUADALAJARA', 'GDL', 'NORTEAMERICA', true),
  ('MONTERREY', 'MTY', 'NORTEAMERICA', true),
  ('LOS CABOS', 'SJD', 'NORTEAMERICA', true),
  ('PUERTO VALLARTA', 'PVR', 'NORTEAMERICA', true),
  ('TIJUANA', 'TIJ', 'NORTEAMERICA', true),
  ('PANAMA', 'PTY', 'CENTROAMERICA Y CARIBE', true),
  ('SAN JOSE COSTA RICA', 'SJO', 'CENTROAMERICA Y CARIBE', true),
  ('LIBERIA', 'LIR', 'CENTROAMERICA Y CARIBE', true),
  ('GUATEMALA', 'GUA', 'CENTROAMERICA Y CARIBE', true),
  ('SAN SALVADOR', 'SAL', 'CENTROAMERICA Y CARIBE', true),
  ('TEGUCIGALPA', 'TGU', 'CENTROAMERICA Y CARIBE', true),
  ('SAN PEDRO SULA', 'SAP', 'CENTROAMERICA Y CARIBE', true),
  ('MANAGUA', 'MGA', 'CENTROAMERICA Y CARIBE', true),
  ('PUNTA CANA', 'PUJ', 'CENTROAMERICA Y CARIBE', true),
  ('SANTO DOMINGO', 'SDQ', 'CENTROAMERICA Y CARIBE', true),
  ('LA HABANA', 'HAV', 'CENTROAMERICA Y CARIBE', true),
  ('VARADERO', 'VRA', 'CENTROAMERICA Y CARIBE', true),
  ('MONTEGO BAY', 'MBJ', 'CENTROAMERICA Y CARIBE', true),
  ('KINGSTON', 'KIN', 'CENTROAMERICA Y CARIBE', true),
  ('ARUBA', 'AUA', 'CENTROAMERICA Y CARIBE', true),
  ('CURAZAO', 'CUR', 'CENTROAMERICA Y CARIBE', true),
  ('SAN JUAN PUERTO RICO', 'SJU', 'CENTROAMERICA Y CARIBE', true),
  ('NASSAU', 'NAS', 'CENTROAMERICA Y CARIBE', true),
  ('BRIDGETOWN', 'BGI', 'CENTROAMERICA Y CARIBE', true),
  ('PUERTO ESPANA', 'POS', 'CENTROAMERICA Y CARIBE', true),
  ('PROVIDENCIALES', 'PLS', 'CENTROAMERICA Y CARIBE', true),
  ('LIMA', 'LIM', 'SURAMERICA', true),
  ('CUSCO', 'CUZ', 'SURAMERICA', true),
  ('QUITO', 'UIO', 'SURAMERICA', true),
  ('GUAYAQUIL', 'GYE', 'SURAMERICA', true),
  ('GALAPAGOS', 'GPS', 'SURAMERICA', true),
  ('SANTIAGO DE CHILE', 'SCL', 'SURAMERICA', true),
  ('BUENOS AIRES', 'EZE', 'SURAMERICA', true),
  ('MENDOZA', 'MDZ', 'SURAMERICA', true),
  ('BARILOCHE', 'BRC', 'SURAMERICA', true),
  ('USHUAIA', 'USH', 'SURAMERICA', true),
  ('SAO PAULO', 'GRU', 'SURAMERICA', true),
  ('RIO DE JANEIRO', 'GIG', 'SURAMERICA', true),
  ('FOZ DE IGUAZU', 'IGU', 'SURAMERICA', true),
  ('SALVADOR DE BAHIA', 'SSA', 'SURAMERICA', true),
  ('FORTALEZA', 'FOR', 'SURAMERICA', true),
  ('LA PAZ', 'LPB', 'SURAMERICA', true),
  ('SANTA CRUZ BOLIVIA', 'VVI', 'SURAMERICA', true),
  ('MONTEVIDEO', 'MVD', 'SURAMERICA', true),
  ('PUNTA DEL ESTE', 'PDP', 'SURAMERICA', true),
  ('ASUNCION', 'ASU', 'SURAMERICA', true),
  ('CARACAS', 'CCS', 'SURAMERICA', true),
  ('PUERTO VARAS', 'PUX', 'SURAMERICA', true),
  ('CALAFATE', 'FTE', 'SURAMERICA', true),
  ('IQUITOS', 'IQT', 'SURAMERICA', true),
  ('AREQUIPA', 'AQP', 'SURAMERICA', true),
  ('MADRID', 'MAD', 'EUROPA', true),
  ('BARCELONA', 'BCN', 'EUROPA', true),
  ('MALAGA', 'AGP', 'EUROPA', true),
  ('SEVILLA', 'SVQ', 'EUROPA', true),
  ('VALENCIA ESPANA', 'VLC', 'EUROPA', true),
  ('PARIS', 'CDG', 'EUROPA', true),
  ('NIZA', 'NCE', 'EUROPA', true),
  ('LONDRES', 'LHR', 'EUROPA', true),
  ('MANCHESTER', 'MAN', 'EUROPA', true),
  ('EDIMBURGO', 'EDI', 'EUROPA', true),
  ('DUBLIN', 'DUB', 'EUROPA', true),
  ('ROMA', 'FCO', 'EUROPA', true),
  ('MILAN', 'MXP', 'EUROPA', true),
  ('VENECIA', 'VCE', 'EUROPA', true),
  ('FLORENCIA', 'FLR', 'EUROPA', true),
  ('NAPOLES', 'NAP', 'EUROPA', true),
  ('LISBOA', 'LIS', 'EUROPA', true),
  ('OPORTO', 'OPO', 'EUROPA', true),
  ('AMSTERDAM', 'AMS', 'EUROPA', true),
  ('BRUSELAS', 'BRU', 'EUROPA', true),
  ('FRANKFURT', 'FRA', 'EUROPA', true),
  ('MUNICH', 'MUC', 'EUROPA', true),
  ('BERLIN', 'BER', 'EUROPA', true),
  ('ZURICH', 'ZRH', 'EUROPA', true),
  ('GINEBRA', 'GVA', 'EUROPA', true),
  ('VIENA', 'VIE', 'EUROPA', true),
  ('PRAGA', 'PRG', 'EUROPA', true),
  ('BUDAPEST', 'BUD', 'EUROPA', true),
  ('ATENAS', 'ATH', 'EUROPA', true),
  ('SANTORINI', 'JTR', 'EUROPA', true),
  ('MICONOS', 'JMK', 'EUROPA', true),
  ('COPENHAGUE', 'CPH', 'EUROPA', true),
  ('ESTOCOLMO', 'ARN', 'EUROPA', true),
  ('OSLO', 'OSL', 'EUROPA', true),
  ('HELSINKI', 'HEL', 'EUROPA', true),
  ('VARSOVIA', 'WAW', 'EUROPA', true),
  ('MOSCU', 'SVO', 'EUROPA', true),
  ('ESTAMBUL', 'IST', 'EUROPA', true),
  ('DUBROVNIK', 'DBV', 'EUROPA', true),
  ('REIKIAVIK', 'KEF', 'EUROPA', true),
  ('DUBAI', 'DXB', 'MEDIO ORIENTE', true),
  ('ABU DABI', 'AUH', 'MEDIO ORIENTE', true),
  ('DOHA', 'DOH', 'MEDIO ORIENTE', true),
  ('TEL AVIV', 'TLV', 'MEDIO ORIENTE', true),
  ('AMMAN', 'AMM', 'MEDIO ORIENTE', true),
  ('TOKIO', 'NRT', 'ASIA', true),
  ('OSAKA', 'KIX', 'ASIA', true),
  ('SEUL', 'ICN', 'ASIA', true),
  ('PEKIN', 'PEK', 'ASIA', true),
  ('SHANGHAI', 'PVG', 'ASIA', true),
  ('HONG KONG', 'HKG', 'ASIA', true),
  ('BANGKOK', 'BKK', 'ASIA', true),
  ('PHUKET', 'HKT', 'ASIA', true),
  ('SINGAPUR', 'SIN', 'ASIA', true),
  ('KUALA LUMPUR', 'KUL', 'ASIA', true),
  ('BALI', 'DPS', 'ASIA', true),
  ('YAKARTA', 'CGK', 'ASIA', true),
  ('HANOI', 'HAN', 'ASIA', true),
  ('HO CHI MINH', 'SGN', 'ASIA', true),
  ('NUEVA DELHI', 'DEL', 'ASIA', true),
  ('MUMBAI', 'BOM', 'ASIA', true),
  ('MALDIVAS', 'MLE', 'ASIA', true),
  ('MANILA', 'MNL', 'ASIA', true),
  ('TAIPEI', 'TPE', 'ASIA', true),
  ('KATMANDU', 'KTM', 'ASIA', true),
  ('SIDNEY', 'SYD', 'OCEANIA', true),
  ('MELBOURNE', 'MEL', 'OCEANIA', true),
  ('BRISBANE', 'BNE', 'OCEANIA', true),
  ('AUCKLAND', 'AKL', 'OCEANIA', true),
  ('PAPEETE', 'PPT', 'OCEANIA', true),
  ('NADI', 'NAN', 'OCEANIA', true)
on conflict (nombre) do update set codigo_iata = excluded.codigo_iata, pais = excluded.pais;