-- Seed inicial del CMS del sitio (contenido actual de lib/sitio/data.js).
-- Idempotente: solo inserta si la tabla está vacía. Correr DESPUÉS de la migración 078.

do $$
begin
  if not exists (select 1 from public.web_paquetes) then
    insert into public.web_paquetes (titulo, region, destino, duracion, personas, precio_desde, descripcion, descripcion_larga, incluye, no_incluye, imagen_url, galeria, destacado, cta_url, orden) values
    ('Cartagena Mágica', 'Nacionales', 'Cartagena, Colombia', '4 días / 3 noches', '2 personas', '599', 'Disfruta de la magia del Caribe colombiano en la ciudad amurallada. Historia, playas y gastronomía en un solo lugar.', 'Vive una experiencia inolvidable en Cartagena de Indias. Este paquete incluye alojamiento en hoteles de primera categoría, tours por la ciudad antigua y visita a las Islas del Rosario. Perfecto para parejas o familias que buscan combinar relax y cultura.', ARRAY['Alojamiento 4 días / 3 noches','Desayunos diarios','Tour Ciudad Amurallada','Visita Islas del Rosario','Traslados Aeropuerto-Hotel-Aeropuerto','Seguro de viaje']::text[], ARRAY['Tiquetes aéreos','Almuerzos y cenas no especificados','Gastos personales']::text[], 'https://images.unsplash.com/photo-1583531352515-8884af319dc1?auto=format&fit=crop&w=800&q=80', ARRAY['https://images.unsplash.com/photo-1628607537594-438235b159b0?auto=format&fit=crop&w=800&q=80','https://images.unsplash.com/photo-1629821861286-398664b86137?auto=format&fit=crop&w=800&q=80']::text[], true, '/tarifario', 0),
    ('San Andrés Paraíso', 'Nacionales', 'San Andrés, Colombia', '5 días / 4 noches', '2 personas', '799', 'El mar de los siete colores te espera. Playas de arena blanca y arrecifes de coral.', 'San Andrés es el destino perfecto para los amantes del sol y la playa. Disfruta de sus aguas cristalinas, practica snorkel en el acuario y da la vuelta a la isla en un carrito de golf.', ARRAY['Alojamiento 5 días / 4 noches','Alimentación Todo Incluido','Tour Vuelta a la Isla','Tour Acuario y Johnny Cay']::text[], ARRAY['Tarjeta de entrada a la isla','Gastos no especificados']::text[], 'https://images.unsplash.com/photo-1544015759-482553e4d763?auto=format&fit=crop&w=800&q=80', ARRAY['https://images.unsplash.com/photo-1621558842707-42a4708049c4?auto=format&fit=crop&w=800&q=80','https://images.unsplash.com/photo-1596563029876-7d3d19c189f1?auto=format&fit=crop&w=800&q=80']::text[], true, '/tarifario', 1),
    ('Eje Cafetero', 'Nacionales', 'Eje Cafetero, Colombia', '3 días / 2 noches', '2 personas', '449', 'Adéntrate en la cultura cafetera. Paisajes verdes, fincas tradicionales y el mejor café del mundo.', 'Recorre los paisajes declarados Patrimonio de la Humanidad por la UNESCO. Visita fincas cafeteras tradicionales, conoce el proceso del café y disfruta de la naturaleza en el Valle del Cocora.', ARRAY['Alojamiento en Finca Hotel','Desayunos','Entrada al Parque del Café','Tour Experiencia Cafetera']::text[], ARRAY['Transporte aéreo','Alimentación no descrita']::text[], 'https://images.unsplash.com/photo-1625156417764-607e4764151e?auto=format&fit=crop&w=800&q=80', ARRAY['https://images.unsplash.com/photo-1531549524-528261695618?auto=format&fit=crop&w=800&q=80','https://images.unsplash.com/photo-1585913494034-3c245a982a60?auto=format&fit=crop&w=800&q=80']::text[], true, '/tarifario', 2),
    ('Punta Cana Dreams', 'Caribe', 'Punta Cana, República Dominicana', '7 días / 6 noches', '2 personas', '1299', 'Lujo y relajación total en el Caribe. Resorts todo incluido y playas infinitas.', 'Escápate a Punta Cana y déjate consentir en los mejores resorts del Caribe. Disfruta de playas de arena blanca, cócteles ilimitados y entretenimiento nocturno.', ARRAY['Alojamiento 7 días / 6 noches','Plan Todo Incluido 24 horas','Traslados Aeropuerto-Hotel-Aeropuerto','Seguro de viaje']::text[], ARRAY['Tiquetes aéreos','Excursiones opcionales']::text[], 'https://images.unsplash.com/photo-1544915220-d2000d9a7a1a?auto=format&fit=crop&w=800&q=80', ARRAY['https://images.unsplash.com/photo-1563911302283-d2bc129e7c1f?auto=format&fit=crop&w=800&q=80','https://images.unsplash.com/photo-1616055192771-677344c26b28?auto=format&fit=crop&w=800&q=80']::text[], true, '/tarifario', 3),
    ('Tour Europa Clásica', 'Europa', 'Madrid, París, Roma', '15 días / 14 noches', '1 persona', '2499', 'Recorre las capitales más emblemáticas de Europa en un viaje inolvidable.', 'Un viaje soñado por el viejo continente. Visita Madrid, París y Roma con guías expertos. Incluye entradas a museos principales y traslados entre ciudades.', ARRAY['Alojamiento en hoteles 4*','Desayunos buffet','Traslados en bus de lujo','Guía en español','Visitas panorámicas']::text[], ARRAY['Vuelos transatlánticos','Tasas turísticas locales','Almuerzos y cenas']::text[], 'https://images.unsplash.com/photo-1499856871940-a09627c6dcf6?auto=format&fit=crop&w=800&q=80', ARRAY['https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80','https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80']::text[], false, '/tarifario', 4),
    ('Escapada Romántica Villa de Leyva', 'Escapadas', 'Villa de Leyva, Colombia', '2 días / 1 noche', '2 personas', '299', 'Un fin de semana mágico en uno de los pueblos más hermosos de Colombia.', 'Desconéctate de la rutina en Villa de Leyva. Cena romántica, caminata por sus calles empedradas y visita a los pozos azules.', ARRAY['Alojamiento en hotel boutique','Desayuno','Cena romántica con vino','Entrada a Pozos Azules']::text[], ARRAY['Transporte desde ciudad de origen','Almuerzos']::text[], 'https://images.unsplash.com/photo-1594406885388-51a0cb790e39?auto=format&fit=crop&w=800&q=80', ARRAY['https://images.unsplash.com/photo-1594406851566-6d216107886c?auto=format&fit=crop&w=800&q=80','https://images.unsplash.com/photo-1591560080990-a6174237e1cb?auto=format&fit=crop&w=800&q=80']::text[], false, '/tarifario', 5),
    ('Cancún All Inclusive', 'Caribe', 'Cancún, México', '6 días / 5 noches', '2 personas', '1199', 'Diversión y sol en el corazón del Caribe Mexicano.', 'Disfruta de las mejores playas de México. Fiesta, cultura maya y relax en un resort todo incluido.', ARRAY['Alojamiento All Inclusive','Traslados','Visita a Cenote']::text[], ARRAY['Vuelos','Impuestos hoteleros']::text[], 'https://images.unsplash.com/photo-1552074291-ad4df87b13ce?auto=format&fit=crop&w=800&q=80', '{}', true, '/tarifario', 6),
    ('Machu Picchu Experience', 'Sudamérica', 'Cusco, Perú', '5 días / 4 noches', '2 personas', '899', 'Descubre la ciudad perdida de los Incas.', 'Una aventura histórica inigualable visitando Cusco, el Valle Sagrado y la maravilla de Machu Picchu.', ARRAY['Hotel','Desayunos','Tren Vistadome','Entradas']::text[], ARRAY['Vuelos internacionales']::text[], 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=800&q=80', '{}', true, '/tarifario', 7);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from public.web_destinos) then
    insert into public.web_destinos (nombre, region, imagen_url, tips, orden) values
    ('Cartagena', 'Caribe', 'https://images.unsplash.com/photo-1583531352515-8884af319dc1?auto=format&fit=crop&w=800&q=80', ARRAY['La mejor época es de diciembre a abril','Lleva ropa ligera y protección solar','Prueba el arroz con coco']::text[], 0),
    ('San Andrés', 'Caribe', 'https://images.unsplash.com/photo-1544015759-482553e4d763?auto=format&fit=crop&w=800&q=80', ARRAY['Compra los zapatos para el mar','Alquila un carrito de golf','Visita Johnny Cay temprano']::text[], 1),
    ('Punta Cana', 'Internacional', 'https://images.unsplash.com/photo-1544915220-d2000d9a7a1a?auto=format&fit=crop&w=800&q=80', ARRAY['Todo incluido es la mejor opción','Lleva repelente de mosquitos','Excursión a Isla Saona es imperdible']::text[], 2),
    ('Madrid', 'Europa', 'https://images.unsplash.com/photo-1543783207-00f3be34372c?auto=format&fit=crop&w=800&q=80', ARRAY['Primavera y otoño tienen el mejor clima','Usa el metro, es muy eficiente','Prueba el bocadillo de calamares']::text[], 3),
    ('Cancún', 'Internacional', 'https://images.unsplash.com/photo-1552074291-ad4df87b13ce?auto=format&fit=crop&w=800&q=80', ARRAY['Visita Chichén Itzá','La zona hotelera es muy segura','Lleva pesos mexicanos para pequeños gastos']::text[], 4),
    ('París', 'Europa', 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80', ARRAY['Compra entradas a museos online','Camina por el barrio de Montmartre','Aprende algunas frases básicas en francés']::text[], 5),
    ('Roma', 'Europa', 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80', ARRAY['Lleva zapatos muy cómodos','Bebe agua de las fuentes públicas','Visita el Vaticano temprano']::text[], 6),
    ('Cusco', 'Sudamérica', 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=800&q=80', ARRAY['Toma mate de coca para la altura','Lleva ropa por capas','Reserva Machu Picchu con meses de antelación']::text[], 7);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from public.web_testimonios) then
    insert into public.web_testimonios (nombre, ubicacion, rating, comentario, imagen_url, orden) values
    ('María González', 'Bogotá', 5, 'Excelente servicio. Mi viaje a Cartagena fue inolvidable gracias a D''Spacios Travel. Todo perfectamente organizado.', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80', 0),
    ('Carlos Ramírez', 'Medellín', 5, 'Los mejores precios del mercado. Reservé un paquete a Cancún y superó todas mis expectativas. Totalmente recomendados.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80', 1),
    ('Ana Martínez', 'Cali', 5, 'Atención personalizada de primer nivel. Me ayudaron a planificar cada detalle de mi luna de miel en Punta Cana.', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80', 2);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from public.web_blog) then
    insert into public.web_blog (titulo, slug, categoria, fecha, resumen, contenido, imagen_url, orden) values
    ('10 Tips para viajar barato a Europa', '10-tips-para-viajar-barato-a-europa', 'Consejos', '15 Oct 2023', 'Descubre cómo ahorrar en vuelos, alojamiento y comida durante tu eurotrip soñado.', 'Viajar a Europa no tiene por qué ser costoso. Planificando con antelación, viajando en temporada baja y utilizando pases de tren, puedes ahorrar significativamente...', 'https://images.unsplash.com/photo-1471623432079-b009d30b6729?auto=format&fit=crop&w=800&q=80', 0),
    ('Mejores playas del Caribe Colombiano', 'mejores-playas-del-caribe-colombiano', 'Destinos', '28 Sep 2023', 'Una guía completa de las joyas ocultas en la costa caribeña de Colombia.', 'Desde el Cabo de la Vela hasta Capurganá, el Caribe colombiano ofrece una diversidad de playas impresionantes...', 'https://images.unsplash.com/photo-1583531352515-8884af319dc1?auto=format&fit=crop&w=800&q=80', 1),
    ('Documentación necesaria para viajar en 2024', 'documentacion-necesaria-para-viajar-en-2024', 'Trámites', '05 Nov 2023', 'Todo lo que necesitas saber sobre pasaportes, visas y requisitos sanitarios actualizados.', 'Antes de empacar tus maletas, asegúrate de tener toda tu documentación en regla. Revisa la vigencia de tu pasaporte...', 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80', 2);
  end if;
end $$;

update public.web_config set whatsapp_numero = coalesce(whatsapp_numero, '573212150582'), hero_titulo = coalesce(hero_titulo, 'D''SPACIOS TRAVEL') where id = 1;
